global:
 scrape_interval: 15s

scrape_configs:
 - job_name: 'frontend'
   static_configs:
     - targets: ['frontend:9100'] # Targets for scraping metrics from the frontend container on port 9100
 - job_name: 'backend'
   static_configs:
     - targets: ['backend:5000', 'backend:9100'] # Targets for scraping metrics from the backend container on ports 5000 and 9100
 - job_name: 'mongodb'
   static_configs:
     - targets: ['mongodb:9100'] # Target for scraping metrics from the MongoDB service/container on port 9100

#Node exporter - 9100
#Node js and express js - 5000