---
- name: Pull Docker images and start containers
  hosts: all
  become: true
  tasks:
    # Create Docker Volume
    - name: Create a volume
      docker_volume:
        name: mongodb_data

    # Create Docker Network of type Bridge
    - name: Create Docker network
      community.docker.docker_network:
        name: "pfa-net"
        driver: "bridge"
        state: present

    # Pull the Mongo Docker Image
    - name: Pull the Mongo Docker Image
      community.docker.docker_image:
        name: "mongo:latest"
        source: pull

    # Create Mongo containers
    - name: Create Mongo container
      community.docker.docker_container:
        name: "pfa-db"
        image: "mongo:latest"
        env:
          MONGO_INITDB_ROOT_USERNAME: "meiezbr"
          MONGO_INITDB_ROOT_PASSWORD: "159357"
        networks:
          - name: "pfa-net"
        volumes:
          - "mongodb_data:/data/db"
        ports:
          - "27017:27017"
        state: started
    
    # Pull the PFA Web App Backend Docker Image
    - name: Pull PFA Web App Backend Docker Image
      community.docker.docker_image:
        name: "meiezbr/web-application-for-managing-university-clubs-activities_backend:latest"
        source: pull

    # Create Backend containers
    - name: Create Backend containers
      community.docker.docker_container:
        name: "pfa-backend"
        image: "meiezbr/web-application-for-managing-university-clubs-activities_backend:latest"
        env:
          MONGODB_HOST: "pfa-db"
          MONGODB_DATABASE: "admin"
          MONGODB_USER: "meiezbr"
          MONGODB_PASSWORD: "159357"
        networks:
          - name: "pfa-net"
        ports:
        - "5000:5000"
        state: started

    # Pull the PFA Web App Frontend Docker Image
    - name: Pull PFA Web App Frontend Docker Image
      community.docker.docker_image:
        name: "meiezbr/web-application-for-managing-university-clubs-activities_frontend:ssl-conf"
        source: pull

    # Create Frontend containers
    - name: Create Frontend containers
      community.docker.docker_container:
        name: pfa-frontend
        image: "meiezbr/web-application-for-managing-university-clubs-activities_frontend:ssl-conf"
        networks:
          - name: "pfa-net"
        ports:
          - "80:80"
          - "443:443"
        volumes:
          - "/home/ubuntu/certbot:/var/www/certbot/:ro"
        state: started