name: CI for Web-Application-For-Managing-University-Clubs-Activities app

on:
  push:
    branches:
      - main

jobs:
  build-and-push-docker-images:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Set up Docker Compose
      - name: Set up Docker Compose
        run: sudo apt-get update && sudo apt-get install docker-compose -y

      # Build images with Docker Compose
      - name: Build images with Docker Compose
        run: docker-compose up -d --build

      # Tag images
      - name: Tag images
        run: |
          docker tag web-application-for-managing-university-clubs-activities_backend ${{ secrets.DOCKER_USERNAME }}/web-application-for-managing-university-clubs-activities_backend:github-actions-ci
          docker tag web-application-for-managing-university-clubs-activities_frontend ${{ secrets.DOCKER_USERNAME }}/web-application-for-managing-university-clubs-activities_frontend:github-actions-ci

      # Push images to Dockerhub
      - name: Push images to Dockerhub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/web-application-for-managing-university-clubs-activities_backend:github-actions-ci
          docker push ${{ secrets.DOCKER_USERNAME }}/web-application-for-managing-university-clubs-activities_frontend:github-actions-ci
